2024-01-26 17:08:45,862 INFO    StreamThr :3042418 [internal.py:wandb_internal():86] W&B internal server running at pid: 3042418, started at: 2024-01-26 17:08:45.861914
2024-01-26 17:08:45,911 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status
2024-01-26 17:08:45,912 INFO    WriterThread:3042418 [datastore.py:open_for_write():87] open: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/run-xoclp9ow.wandb
2024-01-26 17:08:45,912 DEBUG   SenderThread:3042418 [sender.py:send():382] send: header
2024-01-26 17:08:45,912 DEBUG   SenderThread:3042418 [sender.py:send():382] send: run
2024-01-26 17:08:46,840 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: check_version
2024-01-26 17:08:46,854 INFO    SenderThread:3042418 [dir_watcher.py:__init__():211] watching files in: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files
2024-01-26 17:08:46,854 INFO    SenderThread:3042418 [sender.py:_start_run_threads():1136] run started: xoclp9ow with start time 1706260125.843074
2024-01-26 17:08:46,854 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: check_version
2024-01-26 17:08:47,322 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: run_start
2024-01-26 17:08:47,363 DEBUG   HandlerThread:3042418 [system_info.py:__init__():27] System info init
2024-01-26 17:08:47,363 DEBUG   HandlerThread:3042418 [system_info.py:__init__():42] System info init done
2024-01-26 17:08:47,363 INFO    HandlerThread:3042418 [system_monitor.py:start():194] Starting system monitor
2024-01-26 17:08:47,363 INFO    SystemMonitor:3042418 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-26 17:08:47,367 INFO    HandlerThread:3042418 [system_monitor.py:probe():214] Collecting system info
2024-01-26 17:08:47,425 INFO    SystemMonitor:3042418 [interfaces.py:start():190] Started cpu monitoring
2024-01-26 17:08:47,439 INFO    SystemMonitor:3042418 [interfaces.py:start():190] Started disk monitoring
2024-01-26 17:08:47,479 INFO    SystemMonitor:3042418 [interfaces.py:start():190] Started gpu monitoring
2024-01-26 17:08:47,537 INFO    SystemMonitor:3042418 [interfaces.py:start():190] Started memory monitoring
2024-01-26 17:08:47,581 DEBUG   HandlerThread:3042418 [system_info.py:probe():151] Probing system
2024-01-26 17:08:47,586 INFO    SystemMonitor:3042418 [interfaces.py:start():190] Started network monitoring
2024-01-26 17:08:47,622 DEBUG   HandlerThread:3042418 [system_info.py:_probe_git():136] Probing git
2024-01-26 17:08:47,695 DEBUG   HandlerThread:3042418 [system_info.py:_probe_git():144] Probing git done
2024-01-26 17:08:47,695 DEBUG   HandlerThread:3042418 [system_info.py:probe():199] Probing system done
2024-01-26 17:08:47,695 DEBUG   HandlerThread:3042418 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.17', 'python': '3.8.17', 'heartbeatAt': '2024-01-26T09:08:47.581701', 'startedAt': '2024-01-26T09:08:45.792863', 'docker': None, 'cuda': None, 'args': ('--local_rank=3', '--config_file', 'config/bert_pretraining_phase2_config.json', '--input_dir', '/home/yanxindong/mkor/bert/data/encoded/sequences_lowercase_max_seq_len_512_next_seq_task_true', '--output_dir', 'results/adam', '--weight_decay', '0.01', '--num_steps_per_checkpoint', '200'), 'state': 'running', 'program': 'run_pretraining.py', 'codePathLocal': 'run_pretraining.py', 'codePath': 'bert/run_pretraining.py', 'git': {'remote': 'https://github.com/kkkjj-d/mkor.git', 'commit': 'efe99e84fef5594780cfb1df6d6a1f61da4ebba0'}, 'email': '1262670315@qq.com', 'root': '/home/yanxindong/mkor', 'host': 'a6000-X640-G40', 'username': 'yanxindong', 'executable': '/home/yanxindong/anaconda/envs/eva/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 2052.3436406250003, 'min': 800.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3299.998, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2816.254, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2428.172, 'min': 800.0, 'max': 3400.0}, {'current': 2212.735, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1100.0, 'min': 800.0, 'max': 3400.0}, {'current': 3000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2572.163, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2300.82, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2262.64, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1500.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 2300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2408.103, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2369.21, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2339.616, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.002, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2423.786, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1600.0, 'min': 800.0, 'max': 3400.0}, {'current': 1400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1100.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1817.073, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 1630.278, 'min': 800.0, 'max': 3400.0}, {'current': 3300.002, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1776.029, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2044.395, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2205.745, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1857.779, 'min': 800.0, 'max': 3400.0}, {'current': 2645.145, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2272.78, 'min': 800.0, 'max': 3400.0}, {'current': 2281.499, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1403.158, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}], 'disk': {'/': {'total': 438.05088806152344, 'used': 28.042720794677734}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 503.51250076293945}}
2024-01-26 17:08:47,695 INFO    HandlerThread:3042418 [system_monitor.py:probe():224] Finished collecting system info
2024-01-26 17:08:47,695 INFO    HandlerThread:3042418 [system_monitor.py:probe():227] Publishing system info
2024-01-26 17:08:47,695 DEBUG   HandlerThread:3042418 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-26 17:08:47,857 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/conda-environment.yaml
2024-01-26 17:08:57,857 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/conda-environment.yaml
2024-01-26 17:08:58,046 DEBUG   HandlerThread:3042418 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-26 17:08:58,047 INFO    HandlerThread:3042418 [system_monitor.py:probe():229] Finished publishing system info
2024-01-26 17:08:58,053 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:58,058 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:58,059 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:58,059 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:58,059 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: python_packages
2024-01-26 17:08:58,059 DEBUG   SenderThread:3042418 [sender.py:send():382] send: files
2024-01-26 17:08:58,059 INFO    SenderThread:3042418 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-26 17:08:58,060 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: python_packages
2024-01-26 17:08:58,093 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:08:58,094 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:08:58,112 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:08:58,399 DEBUG   SenderThread:3042418 [sender.py:send():382] send: telemetry
2024-01-26 17:08:58,857 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/requirements.txt
2024-01-26 17:08:58,857 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/wandb-metadata.json
2024-01-26 17:08:58,956 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c900c22b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:08:58,957 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:08:58,957 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:00,174 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c901fc880>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:00,175 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:00,175 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:01,400 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:02,192 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c9020e3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:02,192 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:02,192 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:02,192 INFO    wandb-upload_0:3042418 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6c9020e3d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c9020e3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c9020e3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:09:06,400 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:06,806 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c901fcaf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:06,806 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:06,806 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:11,401 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:13,073 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:13,073 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:13,114 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:15,507 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c9020e8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:15,507 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:15,507 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:17,380 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:17,862 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/config.yaml
2024-01-26 17:09:22,844 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:27,878 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:28,094 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:28,094 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:28,121 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:32,178 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c901621c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:32,178 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:32,178 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:33,401 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:38,402 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:43,073 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:43,073 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:43,118 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:45,656 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:47,586 DEBUG   SystemMonitor:3042418 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-26 17:09:47,590 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:09:51,592 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:56,593 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:58,074 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:58,074 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:58,114 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:02,428 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:07,482 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:11,984 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c9020e730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:10:11,984 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:10:11,984 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:10:12,494 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:13,073 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:13,074 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:13,182 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:17,591 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:10:17,594 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:22,593 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:27,593 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:28,073 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:28,074 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:28,110 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:33,246 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:34,049 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/output.log
2024-01-26 17:10:36,049 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/output.log
2024-01-26 17:10:38,246 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:43,247 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:46,175 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:46,175 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:46,179 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:47,593 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:10:48,607 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:53,954 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:58,955 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:01,175 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:01,175 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:01,222 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:04,484 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:09,498 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:14,499 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:16,270 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:16,270 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:16,270 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:17,595 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:11:19,596 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:24,650 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:27,095 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90038670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:11:27,096 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:11:27,096 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:11:29,660 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:31,182 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:31,183 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:31,183 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:35,529 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:40,530 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:45,530 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:46,175 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:46,175 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:46,218 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:47,599 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:11:50,601 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:55,602 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:00,602 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:01,175 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:01,176 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:01,218 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:06,494 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:11,534 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:16,175 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:16,176 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:16,218 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:17,450 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:17,626 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:12:22,627 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:27,708 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:31,175 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:31,176 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:31,217 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:33,524 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:38,588 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:43,609 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:46,176 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:46,176 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:46,218 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:47,634 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:12:48,636 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:53,636 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:58,637 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:01,176 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:01,176 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:01,218 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:04,447 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:09,448 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:14,448 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:16,176 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:16,176 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:16,218 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:17,640 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:13:19,641 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:24,778 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:29,891 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:31,176 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:31,177 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:31,218 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:35,452 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:37,071 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c901fc8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:13:37,071 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:13:37,071 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:13:40,480 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:45,517 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:46,176 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:46,176 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:46,218 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:47,642 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:13:50,771 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:55,781 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:00,858 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:01,176 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:01,177 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:01,217 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:06,482 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:11,482 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:16,183 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:16,183 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:16,184 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:16,501 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:17,644 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:14:21,646 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:26,647 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:31,176 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:31,177 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:31,182 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:32,566 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:37,678 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:42,682 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:46,177 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:46,177 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:46,183 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:47,646 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:14:48,705 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:53,830 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:55,663 DEBUG   SenderThread:3042418 [sender.py:send():382] send: exit
2024-01-26 17:14:55,663 INFO    SenderThread:3042418 [sender.py:send_exit():589] handling exit code: 1
2024-01-26 17:14:55,664 INFO    SenderThread:3042418 [sender.py:send_exit():591] handling runtime: 368
2024-01-26 17:14:55,664 INFO    SenderThread:3042418 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:14:55,664 INFO    SenderThread:3042418 [sender.py:send_exit():597] send defer
2024-01-26 17:14:55,664 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:14:55,664 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 0
2024-01-26 17:14:55,665 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: defer
2024-01-26 17:14:55,665 INFO    SenderThread:3042418 [sender.py:send_request_defer():613] handle sender defer: 0
2024-01-26 17:14:55,665 INFO    SenderThread:3042418 [sender.py:transition_state():617] send defer: 1
2024-01-26 17:14:55,665 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:14:55,665 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 1
2024-01-26 17:14:55,665 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: defer
2024-01-26 17:14:55,665 INFO    SenderThread:3042418 [sender.py:send_request_defer():613] handle sender defer: 1
2024-01-26 17:14:55,665 INFO    SenderThread:3042418 [sender.py:transition_state():617] send defer: 2
2024-01-26 17:14:55,665 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:14:55,665 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 2
2024-01-26 17:14:55,665 INFO    HandlerThread:3042418 [system_monitor.py:finish():203] Stopping system monitor
2024-01-26 17:14:55,665 DEBUG   SystemMonitor:3042418 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-26 17:14:55,665 DEBUG   SystemMonitor:3042418 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-26 17:14:55,668 INFO    HandlerThread:3042418 [interfaces.py:finish():202] Joined cpu monitor
2024-01-26 17:14:55,668 INFO    HandlerThread:3042418 [interfaces.py:finish():202] Joined disk monitor
2024-01-26 17:14:56,079 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/wandb-summary.json
2024-01-26 17:14:57,082 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/output.log
2024-01-26 17:15:04,582 INFO    HandlerThread:3042418 [interfaces.py:finish():202] Joined gpu monitor
2024-01-26 17:15:04,582 INFO    HandlerThread:3042418 [interfaces.py:finish():202] Joined memory monitor
2024-01-26 17:15:04,582 INFO    HandlerThread:3042418 [interfaces.py:finish():202] Joined network monitor
2024-01-26 17:15:04,583 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:04,583 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:04,583 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:04,583 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:04,584 INFO    SenderThread:3042418 [sender.py:send_request_defer():613] handle sender defer: 2
2024-01-26 17:15:04,584 INFO    SenderThread:3042418 [sender.py:transition_state():617] send defer: 3
2024-01-26 17:15:04,584 DEBUG   SenderThread:3042418 [sender.py:send():382] send: stats
2024-01-26 17:15:04,585 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:04,585 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:04,585 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 3
2024-01-26 17:15:04,585 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:04,585 INFO    SenderThread:3042418 [sender.py:send_request_defer():613] handle sender defer: 3
2024-01-26 17:15:04,585 INFO    SenderThread:3042418 [sender.py:transition_state():617] send defer: 4
2024-01-26 17:15:04,585 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:04,585 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 4
2024-01-26 17:15:04,586 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:04,586 INFO    SenderThread:3042418 [sender.py:send_request_defer():613] handle sender defer: 4
2024-01-26 17:15:04,586 INFO    SenderThread:3042418 [sender.py:transition_state():617] send defer: 5
2024-01-26 17:15:04,586 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:04,586 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 5
2024-01-26 17:15:04,586 DEBUG   SenderThread:3042418 [sender.py:send():382] send: summary
2024-01-26 17:15:04,586 INFO    SenderThread:3042418 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:04,587 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:04,587 INFO    SenderThread:3042418 [sender.py:send_request_defer():613] handle sender defer: 5
2024-01-26 17:15:04,587 INFO    SenderThread:3042418 [sender.py:transition_state():617] send defer: 6
2024-01-26 17:15:04,587 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:04,587 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 6
2024-01-26 17:15:04,587 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:04,587 INFO    SenderThread:3042418 [sender.py:send_request_defer():613] handle sender defer: 6
2024-01-26 17:15:04,587 INFO    SenderThread:3042418 [sender.py:transition_state():617] send defer: 7
2024-01-26 17:15:04,587 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:04,587 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:04,587 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 7
2024-01-26 17:15:04,588 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:04,588 INFO    SenderThread:3042418 [sender.py:send_request_defer():613] handle sender defer: 7
2024-01-26 17:15:04,750 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:05,045 INFO    SenderThread:3042418 [sender.py:transition_state():617] send defer: 8
2024-01-26 17:15:05,046 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:05,046 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:05,046 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 8
2024-01-26 17:15:05,046 DEBUG   SenderThread:3042418 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:05,046 INFO    SenderThread:3042418 [sender.py:send_request_defer():613] handle sender defer: 8
2024-01-26 17:15:05,046 INFO    SenderThread:3042418 [job_builder.py:build():296] Attempting to build job artifact
2024-01-26 17:15:05,047 INFO    SenderThread:3042418 [job_builder.py:_get_source_type():426] is repo sourced job
2024-01-26 17:15:05,151 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/output.log
2024-01-26 17:15:05,152 INFO    Thread-12 :3042418 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/wandb-summary.json
2024-01-26 17:15:05,344 INFO    SenderThread:3042418 [job_builder.py:build():402] adding wandb-job metadata file
2024-01-26 17:15:05,347 INFO    SenderThread:3042418 [sender.py:transition_state():617] send defer: 9
2024-01-26 17:15:05,347 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:05,347 INFO    HandlerThread:3042418 [handler.py:handle_request_defer():172] handle defer: 9
2024-01-26 17:15:05,348 DEBUG   SenderThread:3042418 [sender.py:send():382] send: artifact
2024-01-26 17:15:05,751 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:07,227 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c901fc370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:07,227 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:07,227 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:07,772 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c901fcca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:07,772 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:07,772 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:08,439 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90162b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:08,439 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:08,439 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:08,911 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90060ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:08,911 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:08,911 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:08,911 INFO    wandb-upload_2:3042418 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6c90060ac0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90060ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90060ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:15:10,459 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90058160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:10,459 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:10,459 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:10,753 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:10,935 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90060dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:10,935 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:10,935 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:14,543 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c900603d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:14,543 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:14,543 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:15,543 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90060760>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:15,544 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:15,544 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:15,755 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:20,756 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:24,326 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90058580>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:24,326 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:24,326 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:25,200 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90058520>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:25,200 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:25,200 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:25,758 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:30,759 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:35,761 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:40,762 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:43,823 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c900530d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:43,823 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:43,823 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:44,143 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c900513a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:44,143 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:44,143 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:45,766 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:50,767 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:55,769 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:00,771 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:05,774 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:10,776 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:15,779 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:18,130 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c900534c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:18,130 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:18,130 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:20,781 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:22,862 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90162eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:22,862 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:22,862 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:25,783 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:30,785 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:35,787 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:40,789 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:45,792 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:50,794 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:55,796 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:00,799 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:05,800 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:10,802 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:15,805 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:20,806 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:25,102 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90038400>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:17:25,102 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:17:25,102 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:17:25,809 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:30,811 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:35,813 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:40,815 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:42,120 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=kwskgSrk0MgJeXirBIkumTpwHHLlDJJY8Cg4gN8FCEo3Jyh9Upl%2BFICD5VrEizCmyi6pAKLq3zwWxk5bnezeh9QrGUffKtt9z8PsGm33wYeJZv2ZiWcIpgO8uxqR7m5JE0Fgct3NWF57zLgY48zNswzpcrqVQkPQnqmdmqKM6Pyzf0%2Btp53IM4JOtj2hJBPsOWQZ5RNiy6Romu17uKG%2FdF4eePsxAO1mBdrntW5JZlb1ONW7IUjtbaDU7bXK9lBIppfFg4IN1KALE0lGge2kcpaWsvcp3PDT%2FrOeQPMAuOx%2FWWOftMGacbFWsNT3C0L0DcoRqfH4ouckd1PA3znV7g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90038d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:17:42,120 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:17:42,120 ERROR   wandb-upload_1:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:17:45,817 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:50,819 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:55,279 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/xoclp9ow/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZo35r1UY6XLGrfJvpBSiUlIhZaMZR8TzyWm0nZDs7q3as1H5yyj0SWZG%2BfGXL1kxTwg6CbRXe2YUJovNYdCkTbekcTKove0R%2BloN08nLHh9ZozAAICWgPcfAz%2FSXp1rLEk4RpWyes5bnWG0zM9aiteSzVgHEKlzE2jZqiK%2FavaD5fEHAPhLJ1cJVwDCRCOIf4Ah59m25I9mV6r4zlbco8Yw00kt9yKxF%2BuHvDcysuA5FWLhi4%2F76modsjSl2RInOwbIlWl3hXAA%2Bz8Xg4WbrS0eaUQA7yYuZZcKGag%2F0UJwQQTUEDHeYBCgnRR0hyeqmnoaecs7MuMbM7TVoYCsLQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c900585e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:17:55,280 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:17:55,280 ERROR   wandb-upload_0:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:17:55,822 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:00,824 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:05,826 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:10,828 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:15,831 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:20,833 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:25,835 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:30,838 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:35,840 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:40,842 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:45,844 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:50,846 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:55,848 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:00,850 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:05,852 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:10,853 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:15,856 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:20,858 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:25,860 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:30,862 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:34,980 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789176/6873c23a2381d1524249eb1a948a45a5?Expires=1706346907&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jBMbp2%2BWINAKzEYxNvERenqiLhph%2BlLK5LeURmYknGvgI42%2FgogC8%2BVam7K0xnmmGsy72ZfERQcP0Z8E2OHVwF6OIHI8xN9JI2M8v9s4YF%2BPnaD1%2F9disGe5LaC%2Fb%2FTUXRfhg3hy3vaQo%2F%2BU1brFQMVeU7LbdByduxf37d9rmLVE0YhleRef%2F2PDD6F63xgZeXt26sMQswhZutAPcpid0sLUxx06pmk0l6KlGp2voA8Y7jW7IhJqFbCnxT1sPhLRRLh0AW5yhbzebBNtOAMXR9W8NCtG3AZpLARPxlh%2BrYltQZO%2F8K7Mru4kq0pa2lsNClNI6Bl8tv3EThIe46qKFw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c90051f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:19:34,980 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:19:34,980 ERROR   wandb-upload_2:3042418 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:19:35,866 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:40,868 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:45,870 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:50,872 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:55,874 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:00,876 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:05,646 INFO    wandb-upload_1:3042418 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmpcwm82k40
2024-01-26 17:20:05,878 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:10,879 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:15,882 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:20,884 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:25,886 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:30,888 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:35,891 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:40,893 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:45,896 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:50,898 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:55,900 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:00,902 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:05,904 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:10,906 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:15,908 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:20,910 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:25,912 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:30,914 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:35,917 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:40,919 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:45,921 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:50,923 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:21:55,925 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:00,927 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:05,929 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:10,932 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:15,934 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:20,937 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:25,938 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:30,940 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:35,943 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:40,945 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:45,947 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:50,949 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:22:55,951 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:00,954 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:05,956 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:10,958 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:15,959 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:20,961 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:25,963 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:30,965 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:35,967 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:40,970 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:45,972 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:50,974 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:23:55,975 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:24:00,977 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:24:05,979 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:24:10,435 INFO    wandb-upload_0:3042418 [upload_job.py:push():131] Uploaded file /tmp/tmp8azfgv_6wandb/qx9i55ia-wandb-metadata.json
2024-01-26 17:24:10,982 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:24:15,984 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:24:20,985 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:24:25,988 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:24:30,989 DEBUG   HandlerThread:3042418 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:24:34,700 WARNING StreamThr :3042418 [internal.py:is_dead():414] Internal process exiting, parent pid 3042148 disappeared
2024-01-26 17:24:34,700 ERROR   StreamThr :3042418 [internal.py:wandb_internal():152] Internal process shutdown.
2024-01-26 17:24:34,829 INFO    WriterThread:3042418 [datastore.py:close():296] close: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/run-xoclp9ow.wandb
2024-01-26 17:24:34,990 INFO    HandlerThread:3042418 [handler.py:finish():869] shutting down handler
2024-01-26 17:24:40,503 INFO    wandb-upload_2:3042418 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmptw2pqcsx
2024-01-26 17:24:45,915 INFO    SenderThread:3042418 [sender.py:send_artifact():1494] sent artifact job-https___github.com_kkkjj-d_mkor.git_bert_run_pretraining.py - {'id': 'QXJ0aWZhY3Q6NzAzNzg5MTc2', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjEzMzk4MTIwMA==', 'latestArtifact': None}}
2024-01-26 17:24:45,915 INFO    SenderThread:3042418 [sender.py:finish():1572] shutting down sender
2024-01-26 17:24:45,915 INFO    SenderThread:3042418 [dir_watcher.py:finish():358] shutting down directory watcher
2024-01-26 17:24:46,251 INFO    SenderThread:3042418 [dir_watcher.py:finish():388] scan: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files
2024-01-26 17:24:46,251 INFO    SenderThread:3042418 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/wandb-summary.json wandb-summary.json
2024-01-26 17:24:46,251 INFO    SenderThread:3042418 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/conda-environment.yaml conda-environment.yaml
2024-01-26 17:24:46,252 INFO    SenderThread:3042418 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/wandb-metadata.json wandb-metadata.json
2024-01-26 17:24:46,252 INFO    SenderThread:3042418 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/output.log output.log
2024-01-26 17:24:46,252 INFO    SenderThread:3042418 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/requirements.txt requirements.txt
2024-01-26 17:24:46,254 INFO    SenderThread:3042418 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/config.yaml config.yaml
2024-01-26 17:24:46,258 INFO    SenderThread:3042418 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:24:46,258 INFO    SenderThread:3042418 [file_pusher.py:join():181] waiting for file pusher
2024-01-26 17:24:46,892 INFO    wandb-upload_1:3042418 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/wandb-summary.json
2024-01-26 17:24:47,456 INFO    wandb-upload_3:3042418 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/requirements.txt
2024-01-26 17:24:47,482 INFO    wandb-upload_4:3042418 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/config.yaml
2024-01-26 17:24:47,520 INFO    wandb-upload_0:3042418 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/output.log
2024-01-26 17:24:48,049 INFO    wandb-upload_2:3042418 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-xoclp9ow/files/conda-environment.yaml
2024-01-26 17:24:48,260 INFO    SenderThread:3042418 [file_stream.py:finish():595] file stream finish called
2024-01-26 17:24:48,604 INFO    SenderThread:3042418 [file_stream.py:finish():599] file stream finish is done
